language: cpp
dist: trusty
sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - bc
            - expect
            - gettext
            - libncurses5-dev
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - bc
            - expect
            - gettext
            - lib32ncurses5-dev
            - g++-multilib
      env:
        - CXXFLAGS="-g -m32" CFLAGS="-g -m32"
    - os: linux
      compiler: clang
      env:
          - CXXFLAGS="-g -fno-omit-frame-pointer -fsanitize=address" ASAN_OPTIONS=check_initialization_order=1:detect_stack_use_after_return=1:detect_leaks=1
      before_install: export CXX=clang++-3.8
      addons:
        apt:
          sources:
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.8
            - llvm-3.8 # for llvm-symbolizer
            - bc
            - expect
            - gettext
            - libncurses5-dev
    - os: osx
      osx_image: xcode8
      before_install:
        - brew update
        - brew install pcre2 gnu-tar doxygen # use system PCRE2
        - brew outdated xctool || brew upgrade xctool # for xcode... soon.
      env:
        - CXXFLAGS="-g -lstdc++"
      before_deploy:
        - mkdir -p $HOME/staged
        - env FISH_ARTEFACT_PATH=$HOME/staged ./build_tools/make_tarball.sh
  fast_finish: true

script:
  - autoreconf
  - ./configure --prefix=$HOME/prefix || cat config.log
  - make -j2
  - make install
  - make test DESTDIR=$HOME/prefix/ SHOW_INTERACTIVE_LOG=1

notifications:
  # Some items are encrypted so that notifications from other repositories
  # don't flood the official repositories.
  irc:
    channels:
        #- "irc.oftc.net#fish"
        secure: "eRk9KGZ5+mrlD2SoI8yg2Sp8OYrh7YPyGe3WCDQUwTnNgNDII34rbM9a6UOA/l7AeWSNY8joLq5xVLCU4wpFgUcJ11SYIpMnLosZK29OW4ubDOHmdBDvJ971rLgAVG9cXngZtIxEVVxN/jnS1Qr8GKZx4DjkaTMgz1pemb4WxCc="
    template:
      - "%{repository}#%{build_number} (%{commit} on %{branch} by %{author}): %{message} Details at %{build_url}"
    use_notice: true
    skip_join: true
  webhooks:
    urls:
      #- https://webhooks.gitter.im/e/61821cec3015bf0f8bb1
      secure: fPfOmxnC3MCsfR1oocVFeWLawGcRZkn+8fNHlSOeZ+SqqoZfcCHgQTvQ22TqmVl1yvkXbNlaXjo6dbVzTOAh7r7H0bRMEKBVh3dQS7wqjB1sKivpXd8PAS3BTj5MQpGeJzdHnDuwVlwDktGtfHfhGeq1Go/4IosOq8u+6RTe28g=

deploy:
  provider: s3
  access_key_id:
    secure: "jxFz+eAyP7AkIQ+70iw2se853eR0aSLX5WlzS2WhM3uMmtV0k5W+yPJx5tgfN/XfXTr7QOmYG0KpqYoAmwpWFagn/2hE3JAoYZlblaKC8isEnWpucBscAG/4qDKP5y9b+WOfQ+eCjOUsgvXJw/yrBQ+J5mWaYEcO07N599jI/n0="
  secret_access_key:
    secure: IpCEQ3Hbx6dMuFTLgyH2JVJnMt5BaFNbq+aEbhCRieVE7FamgDnPhZ2vbF9yDZLmVLvdtkXVsGp3UFFanGnYS0pO7Fa45rHHnmvA7sNvjZfnf6ctd7vV/XJoFk42pAmcUyZZ7RU3hulILQW3PDaqSL+4gquKgCZyMAhiNYzsZSU=
  bucket: fishshell.com
  local-dir: staged
  upload-dir: travis_uploaded
  acl: public_read
  skip_cleanup: true
  on:
    repo: fish-shell/fish-shell
    branch: macos_continuous_deployment_experiment
    condition: $TRAVIS_OS_NAME = linux
